name:                teapot
version:             0.1.0.0
github:              "CNoctem/teapot"
license:             BSD3
author:              "frozengoatmilk"
copyright:           "2022 frozengoatmilk"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- mtl
- text
- scotty
- http-types

default-extensions:
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - OverloadedStrings

executables:
  teapot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
